In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = pd.read_csv("Telco_FeatureEngineered.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Telco_FeatureEngineered.csv'

In [9]:
import os

print(os.listdir("Project"))

['.ipynb_checkpoints', 'table.sql', 'Telco_Cleaned.csv', 'Telco_FeatureEngineered.csv', 'Untitled.ipynb', 'Untitled1.ipynb', 'WA_Fn-UseC_-Telco-Customer-Churn.csv', 'Week_1_EDA_Data_Preprocessing.ipynb']

In [10]:
df = pd.read_csv("Project/Telco_FeatureEngineered.csv")

In [11]:
df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,PaymentMethod_Electronic check,PaymentMethod_Mailed check,AvgChargePerMonth,TotalServices,TenureGroup_New,TenureGroup_Regular,TenureGroup_Very Loyal,ChargeCategory_Low,ChargeCategory_Medium,HighValueCustomer
0,0,1,29.85,29.85,0,False,True,False,False,True,...,True,False,14.925000,1,True,False,False,True,False,0
1,0,34,56.95,1889.50,0,True,False,False,True,False,...,False,True,53.985714,3,False,True,False,False,True,0
2,0,2,53.85,108.15,1,True,False,False,True,False,...,False,True,36.050000,3,True,False,False,False,True,0
3,0,45,42.30,1840.75,0,True,False,False,False,True,...,False,False,40.016304,3,False,False,False,False,True,0
4,0,2,70.70,151.65,1,False,False,False,True,False,...,True,False,50.550000,1,True,False,False,False,False,0

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 39 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7032 non-null   int64
 1   tenure                                 7032 non-null   int64
 2   MonthlyCharges                         7032 non-null   float64
 3   TotalCharges                           7032 non-null   float64
 4   Churn                                  7032 non-null   int64
 5   gender_Male                            7032 non-null   bool
 6   Partner_Yes                            7032 non-null   bool
 7   Dependents_Yes                         7032 non-null   bool
 8   PhoneService_Yes                       7032 non-null   bool
 9   MultipleLines_No phone service         7032 non-null   bool
 10  MultipleLines_Yes                      7032 non-null   bool
 11  InternetService_Fiber optic            7032 non-null   bool
 12  InternetService_No                     7032 non-null   bool
 13  OnlineSecurity_No internet service     7032 non-null   bool
 14  OnlineSecurity_Yes                     7032 non-null   bool
 15  OnlineBackup_No internet service       7032 non-null   bool
 16  OnlineBackup_Yes                       7032 non-null   bool
 17  DeviceProtection_No internet service   7032 non-null   bool
 18  DeviceProtection_Yes                   7032 non-null   bool
 19  TechSupport_No internet service        7032 non-null   bool
 20  TechSupport_Yes                        7032 non-null   bool
 21  StreamingTV_No internet service        7032 non-null   bool
 22  StreamingTV_Yes                        7032 non-null   bool
 23  StreamingMovies_No internet service    7032 non-null   bool
 24  StreamingMovies_Yes                    7032 non-null   bool
 25  Contract_One year                      7032 non-null   bool
 26  Contract_Two year                      7032 non-null   bool
 27  PaperlessBilling_Yes                   7032 non-null   bool
 28  PaymentMethod_Credit card (automatic)  7032 non-null   bool
 29  PaymentMethod_Electronic check         7032 non-null   bool
 30  PaymentMethod_Mailed check             7032 non-null   bool
 31  AvgChargePerMonth                      7032 non-null   float64
 32  TotalServices                          7032 non-null   int64
 33  TenureGroup_New                        7032 non-null   bool
 34  TenureGroup_Regular                    7032 non-null   bool
 35  TenureGroup_Very Loyal                 7032 non-null   bool
 36  ChargeCategory_Low                     7032 non-null   bool
 37  ChargeCategory_Medium                  7032 non-null   bool
 38  HighValueCustomer                      7032 non-null   int64
dtypes: bool(31), float64(3), int64(5)
memory usage: 652.5 KB

In [13]:
df.shape

(7032, 39)

In [14]:
df.describe()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,AvgChargePerMonth,TotalServices,HighValueCustomer
count,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000
mean,0.162400,32.421786,64.798208,2283.300441,0.265785,59.083067,3.363339,0.317122
std,0.368844,24.545260,30.085974,2266.771362,0.441782,30.514438,2.062067,0.465388
min,0.000000,1.000000,18.250000,18.800000,0.000000,9.183333,0.000000,0.000000
25%,0.000000,9.000000,35.587500,401.450000,0.000000,26.225944,1.000000,0.000000
50%,0.000000,29.000000,70.350000,1397.475000,0.000000,61.070387,3.000000,0.000000
75%,0.000000,55.000000,89.862500,3794.737500,1.000000,84.877538,5.000000,1.000000
max,1.000000,72.000000,118.750000,8684.800000,1.000000,118.969863,8.000000,1.000000

In [15]:
df["EstimatedLTV"] = df["MonthlyCharges"] * df["tenure"]

In [16]:
df[["MonthlyCharges","tenure","EstimatedLTV"]].head()

   MonthlyCharges  tenure  EstimatedLTV
0           29.85       1         29.85
1           56.95      34       1936.30
2           53.85       2        107.70
3           42.30      45       1903.50
4           70.70       2        141.40

In [17]:
df["RevenueSegment"] = pd.qcut(
    df["EstimatedLTV"],
    q=4,
    labels=["Bronze","Silver","Gold","Platinum"]
)

In [18]:
df["RevenueSegment"].value_counts()

RevenueSegment
Bronze      1759
Gold        1758
Platinum    1758
Silver      1757
Name: count, dtype: int64

In [19]:
df["CustomerValueScore"] = (
    df["TotalServices"] * 2
    + df["tenure"] / 12
    + df["MonthlyCharges"] / 10
)

In [20]:
df[["CustomerValueScore"]].head()

   CustomerValueScore
0            5.068333
1           14.528333
2           11.551667
3           13.980000
4            9.236667

In [21]:
df["HighValueCustomer"] = np.where(
    df["CustomerValueScore"] >= df["CustomerValueScore"].median(),
    1,
    0
)

In [22]:
df["HighValueCustomer"].value_counts()

HighValueCustomer
1    3517
0    3515
Name: count, dtype: int64

In [23]:
df.to_csv("Telco_LTV_FeatureEngineered.csv", index=False)

In [24]:
print(df.columns)

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'AvgChargePerMonth', 'TotalServices', 'TenureGroup_New',
       'TenureGroup_Regular', 'TenureGroup_Very Loyal', 'ChargeCategory_Low',
       'ChargeCategory_Medium', 'HighValueCustomer', 'EstimatedLTV',
       'RevenueSegment', 'CustomerValueScore'],
      dtype='str')