In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("Telco_Cleaned.csv")

df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,False,True,False,False,True,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,0,True,False,False,True,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,1,True,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,0,True,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,1,False,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False

In [9]:
 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7043 non-null   int64
 1   tenure                                 7043 non-null   int64
 2   MonthlyCharges                         7043 non-null   float64
 3   TotalCharges                           7032 non-null   float64
 4   Churn                                  7043 non-null   int64
 5   gender_Male                            7043 non-null   bool
 6   Partner_Yes                            7043 non-null   bool
 7   Dependents_Yes                         7043 non-null   bool
 8   PhoneService_Yes                       7043 non-null   bool
 9   MultipleLines_No phone service         7043 non-null   bool
 10  MultipleLines_Yes                      7043 non-null   bool
 11  InternetService_Fiber optic            7043 non-null   bool
 12  InternetService_No                     7043 non-null   bool
 13  OnlineSecurity_No internet service     7043 non-null   bool
 14  OnlineSecurity_Yes                     7043 non-null   bool
 15  OnlineBackup_No internet service       7043 non-null   bool
 16  OnlineBackup_Yes                       7043 non-null   bool
 17  DeviceProtection_No internet service   7043 non-null   bool
 18  DeviceProtection_Yes                   7043 non-null   bool
 19  TechSupport_No internet service        7043 non-null   bool
 20  TechSupport_Yes                        7043 non-null   bool
 21  StreamingTV_No internet service        7043 non-null   bool
 22  StreamingTV_Yes                        7043 non-null   bool
 23  StreamingMovies_No internet service    7043 non-null   bool
 24  StreamingMovies_Yes                    7043 non-null   bool
 25  Contract_One year                      7043 non-null   bool
 26  Contract_Two year                      7043 non-null   bool
 27  PaperlessBilling_Yes                   7043 non-null   bool
 28  PaymentMethod_Credit card (automatic)  7043 non-null   bool
 29  PaymentMethod_Electronic check         7043 non-null   bool
 30  PaymentMethod_Mailed check             7043 non-null   bool
dtypes: bool(26), float64(2), int64(3)
memory usage: 454.1 KB

In [10]:
df["AvgChargePerMonth"] = df["TotalCharges"] / (df["tenure"] + 1)

In [11]:
df[["MonthlyCharges","TotalCharges","AvgChargePerMonth"]].head()

   MonthlyCharges  TotalCharges  AvgChargePerMonth
0           29.85         29.85          14.925000
1           56.95       1889.50          53.985714
2           53.85        108.15          36.050000
3           42.30       1840.75          40.016304
4           70.70        151.65          50.550000

In [12]:
df["TenureGroup"] = pd.cut(
    df["tenure"],
    bins=[0,12,36,60,72],
    labels=["New","Regular","Loyal","Very Loyal"]
)

In [13]:
df["TenureGroup"].value_counts()

TenureGroup
New           2175
Regular       1856
Loyal         1594
Very Loyal    1407
Name: count, dtype: int64

In [14]:
df["ChargeCategory"] = pd.cut(
    df["MonthlyCharges"],
    bins=[0,35,70,120],
    labels=["Low","Medium","High"]
)

In [15]:
df["ChargeCategory"].value_counts()

ChargeCategory
High      3583
Low       1735
Medium    1725
Name: count, dtype: int64

In [16]:
service_columns = [
    "PhoneService_Yes",
    "MultipleLines_Yes",
    "OnlineSecurity_Yes",
    "OnlineBackup_Yes",
    "DeviceProtection_Yes",
    "TechSupport_Yes",
    "StreamingTV_Yes",
    "StreamingMovies_Yes"
]

df["TotalServices"] = df[service_columns].sum(axis=1)

In [17]:
df[["TotalServices"]].head()

   TotalServices
0              1
1              3
2              3
3              3
4              1

In [18]:
df.to_csv("Telco_LTV_FeatureEngineered.csv", index=False)

In [19]:
print(df.columns)

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'AvgChargePerMonth', 'TenureGroup', 'ChargeCategory', 'TotalServices'],
      dtype='str')

In [20]:
df["CustomerEngagementScore"] = (
    df["TotalServices"] * 2 + (df["tenure"] / 12)
).round(2)

df[["CustomerEngagementScore"]].head()

   CustomerEngagementScore
0                     2.08
1                     8.83
2                     6.17
3                     9.75
4                     2.17

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [22]:
df["EstimatedLTV"] = df["MonthlyCharges"] * df["tenure"]

df[["MonthlyCharges", "tenure", "EstimatedLTV"]].head()

   MonthlyCharges  tenure  EstimatedLTV
0           29.85       1         29.85
1           56.95      34       1936.30
2           53.85       2        107.70
3           42.30      45       1903.50
4           70.70       2        141.40

In [23]:
df["EstimatedLTV"].describe()

count    7043.000000
mean     2279.581350
std      2264.729447
min         0.000000
25%       394.000000
50%      1393.600000
75%      3786.100000
max      8550.000000
Name: EstimatedLTV, dtype: float64

In [24]:
X = df.drop("EstimatedLTV", axis=1)

y = df["EstimatedLTV"]

In [25]:
X = pd.get_dummies(
    X,
    columns=["TenureGroup", "ChargeCategory"],
    drop_first=True
)

In [26]:
bool_cols = X.select_dtypes(include="bool").columns

X[bool_cols] = X[bool_cols].astype(int)

In [27]:
print(X.isnull().sum().sum())

22

In [28]:
print(X.isnull().sum()[X.isnull().sum() > 0])

TotalCharges         11
AvgChargePerMonth    11
dtype: int64

In [29]:
X["TotalCharges"] = X["TotalCharges"].fillna(X["TotalCharges"].median())

X["AvgChargePerMonth"] = X["AvgChargePerMonth"].fillna(
    X["AvgChargePerMonth"].median()
)

In [30]:
print(X.isnull().sum().sum())

0

In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [32]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [33]:
lr = LinearRegression()

lr.fit(X_train_scaled, y_train)

LinearRegression()

In [34]:
y_pred_lr = lr.predict(X_test_scaled)

In [35]:
print("MAE :", mean_absolute_error(y_test, y_pred_lr))

print("RMSE :", mean_squared_error(y_test, y_pred_lr) ** 0.5)

print("R² Score :", r2_score(y_test, y_pred_lr))

MAE : 51.60772669972285
RMSE : 76.65369144381042
R² Score : 0.9988709104771395

In [36]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [37]:
y_pred_rf = rf.predict(X_test)

In [38]:
print("Random Forest Results")
print("----------------------")
print("MAE :", mean_absolute_error(y_test, y_pred_rf))
print("RMSE :", mean_squared_error(y_test, y_pred_rf) ** 0.5)
print("R² Score :", r2_score(y_test, y_pred_rf))

Random Forest Results
----------------------
MAE : 39.61116181689141
RMSE : 61.295519969121415
R² Score : 0.9992780290949984

In [39]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    random_state=42,
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5
)

xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [40]:
y_pred_xgb = xgb.predict(X_test)

In [41]:
print("XGBoost Results")
print("----------------")
print("MAE :", mean_absolute_error(y_test, y_pred_xgb))
print("RMSE :", mean_squared_error(y_test, y_pred_xgb) ** 0.5)
print("R² Score :", r2_score(y_test, y_pred_xgb))

XGBoost Results
----------------
MAE : 32.21242874123849
RMSE : 49.52054063507282
R² Score : 0.999528769942855

In [42]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest", "XGBoost"],
    "MAE": [
        mean_absolute_error(y_test, y_pred_lr),
        mean_absolute_error(y_test, y_pred_rf),
        mean_absolute_error(y_test, y_pred_xgb)
    ],
    "RMSE": [
        mean_squared_error(y_test, y_pred_lr) ** 0.5,
        mean_squared_error(y_test, y_pred_rf) ** 0.5,
        mean_squared_error(y_test, y_pred_xgb) ** 0.5
    ],
    "R2 Score": [
        r2_score(y_test, y_pred_lr),
        r2_score(y_test, y_pred_rf),
        r2_score(y_test, y_pred_xgb)
    ]
})

results

               Model        MAE       RMSE  R2 Score
0  Linear Regression  51.607727  76.653691  0.998871
1      Random Forest  39.611162  61.295520  0.999278
2            XGBoost  32.212429  49.520541  0.999529

In [47]:
print(results.columns)

Index(['Model', 'MAE', 'RMSE', 'R2 Score'], dtype='str')

In [48]:
"R2 Score"

'R2 Score'

In [49]:
best_model = results.sort_values(
    by="R2 Score",
    ascending=False
)

best_model

               Model        MAE       RMSE  R2 Score
2            XGBoost  32.212429  49.520541  0.999529
1      Random Forest  39.611162  61.295520  0.999278
0  Linear Regression  51.607727  76.653691  0.998871

In [51]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest", "XGBoost"],
    "MAE": [
        mean_absolute_error(y_test, y_pred_lr),
        mean_absolute_error(y_test, y_pred_rf),
        mean_absolute_error(y_test, y_pred_xgb)
    ],
    "RMSE": [
        mean_squared_error(y_test, y_pred_lr) ** 0.5,
        mean_squared_error(y_test, y_pred_rf) ** 0.5,
        mean_squared_error(y_test, y_pred_xgb) ** 0.5
    ],
    "R2_Score": [
        r2_score(y_test, y_pred_lr),
        r2_score(y_test, y_pred_rf),
        r2_score(y_test, y_pred_xgb)
    ]
})

results

               Model        MAE       RMSE  R2_Score
0  Linear Regression  51.607727  76.653691  0.998871
1      Random Forest  39.611162  61.295520  0.999278
2            XGBoost  32.212429  49.520541  0.999529

In [52]:
best_model = results.sort_values(
    by="R2_Score",
    ascending=False
)

best_model

               Model        MAE       RMSE  R2_Score
2            XGBoost  32.212429  49.520541  0.999529
1      Random Forest  39.611162  61.295520  0.999278
0  Linear Regression  51.607727  76.653691  0.998871